// Code generated by MockGen. DO NOT EDIT.
// Source: internal/events/publisher.go
//
// Generated by this command:
//
//	mockgen -source=internal/events/publisher.go -destination=internal/mocks/events_mock.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
	isgomock struct{}
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockPublisher) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockPublisherMockRecorder) Close() *MockPublisherCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPublisher)(nil).Close))
	return &MockPublisherCloseCall{Call: call}
}

// MockPublisherCloseCall wrap *gomock.Call
type MockPublisherCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPublisherCloseCall) Return(arg0 error) *MockPublisherCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPublisherCloseCall) Do(f func() error) *MockPublisherCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPublisherCloseCall) DoAndReturn(f func() error) *MockPublisherCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Publish mocks base method.
func (m *MockPublisher) Publish(eventType string, payload any, metadata map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", eventType, payload, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockPublisherMockRecorder) Publish(eventType, payload, metadata any) *MockPublisherPublishCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockPublisher)(nil).Publish), eventType, payload, metadata)
	return &MockPublisherPublishCall{Call: call}
}

// MockPublisherPublishCall wrap *gomock.Call
type MockPublisherPublishCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPublisherPublishCall) Return(arg0 error) *MockPublisherPublishCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPublisherPublishCall) Do(f func(string, any, map[string]string) error) *MockPublisherPublishCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPublisherPublishCall) DoAndReturn(f func(string, any, map[string]string) error) *MockPublisherPublishCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
