// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repositories/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/repositories/interfaces.go -destination=internal/mocks/repositories_mock.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "github.com/m0xyu/learning-go-shop/internal/dto"
	models "github.com/m0xyu/learning-go-shop/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepositoryInterface is a mock of UserRepositoryInterface interface.
type MockUserRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockUserRepositoryInterfaceMockRecorder is the mock recorder for MockUserRepositoryInterface.
type MockUserRepositoryInterfaceMockRecorder struct {
	mock *MockUserRepositoryInterface
}

// NewMockUserRepositoryInterface creates a new mock instance.
func NewMockUserRepositoryInterface(ctrl *gomock.Controller) *MockUserRepositoryInterface {
	mock := &MockUserRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepositoryInterface) EXPECT() *MockUserRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepositoryInterface) Create(user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryInterfaceMockRecorder) Create(user any) *MockUserRepositoryInterfaceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepositoryInterface)(nil).Create), user)
	return &MockUserRepositoryInterfaceCreateCall{Call: call}
}

// MockUserRepositoryInterfaceCreateCall wrap *gomock.Call
type MockUserRepositoryInterfaceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryInterfaceCreateCall) Return(arg0 error) *MockUserRepositoryInterfaceCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryInterfaceCreateCall) Do(f func(*models.User) error) *MockUserRepositoryInterfaceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryInterfaceCreateCall) DoAndReturn(f func(*models.User) error) *MockUserRepositoryInterfaceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateRefreshToken mocks base method.
func (m *MockUserRepositoryInterface) CreateRefreshToken(token *models.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefreshToken", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRefreshToken indicates an expected call of CreateRefreshToken.
func (mr *MockUserRepositoryInterfaceMockRecorder) CreateRefreshToken(token any) *MockUserRepositoryInterfaceCreateRefreshTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefreshToken", reflect.TypeOf((*MockUserRepositoryInterface)(nil).CreateRefreshToken), token)
	return &MockUserRepositoryInterfaceCreateRefreshTokenCall{Call: call}
}

// MockUserRepositoryInterfaceCreateRefreshTokenCall wrap *gomock.Call
type MockUserRepositoryInterfaceCreateRefreshTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryInterfaceCreateRefreshTokenCall) Return(arg0 error) *MockUserRepositoryInterfaceCreateRefreshTokenCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryInterfaceCreateRefreshTokenCall) Do(f func(*models.RefreshToken) error) *MockUserRepositoryInterfaceCreateRefreshTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryInterfaceCreateRefreshTokenCall) DoAndReturn(f func(*models.RefreshToken) error) *MockUserRepositoryInterfaceCreateRefreshTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockUserRepositoryInterface) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserRepositoryInterfaceMockRecorder) Delete(id any) *MockUserRepositoryInterfaceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserRepositoryInterface)(nil).Delete), id)
	return &MockUserRepositoryInterfaceDeleteCall{Call: call}
}

// MockUserRepositoryInterfaceDeleteCall wrap *gomock.Call
type MockUserRepositoryInterfaceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryInterfaceDeleteCall) Return(arg0 error) *MockUserRepositoryInterfaceDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryInterfaceDeleteCall) Do(f func(uint) error) *MockUserRepositoryInterfaceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryInterfaceDeleteCall) DoAndReturn(f func(uint) error) *MockUserRepositoryInterfaceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteRefreshToken mocks base method.
func (m *MockUserRepositoryInterface) DeleteRefreshToken(token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshToken", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshToken indicates an expected call of DeleteRefreshToken.
func (mr *MockUserRepositoryInterfaceMockRecorder) DeleteRefreshToken(token any) *MockUserRepositoryInterfaceDeleteRefreshTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshToken", reflect.TypeOf((*MockUserRepositoryInterface)(nil).DeleteRefreshToken), token)
	return &MockUserRepositoryInterfaceDeleteRefreshTokenCall{Call: call}
}

// MockUserRepositoryInterfaceDeleteRefreshTokenCall wrap *gomock.Call
type MockUserRepositoryInterfaceDeleteRefreshTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryInterfaceDeleteRefreshTokenCall) Return(arg0 error) *MockUserRepositoryInterfaceDeleteRefreshTokenCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryInterfaceDeleteRefreshTokenCall) Do(f func(string) error) *MockUserRepositoryInterfaceDeleteRefreshTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryInterfaceDeleteRefreshTokenCall) DoAndReturn(f func(string) error) *MockUserRepositoryInterfaceDeleteRefreshTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteRefreshTokenByID mocks base method.
func (m *MockUserRepositoryInterface) DeleteRefreshTokenByID(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshTokenByID", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshTokenByID indicates an expected call of DeleteRefreshTokenByID.
func (mr *MockUserRepositoryInterfaceMockRecorder) DeleteRefreshTokenByID(id any) *MockUserRepositoryInterfaceDeleteRefreshTokenByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshTokenByID", reflect.TypeOf((*MockUserRepositoryInterface)(nil).DeleteRefreshTokenByID), id)
	return &MockUserRepositoryInterfaceDeleteRefreshTokenByIDCall{Call: call}
}

// MockUserRepositoryInterfaceDeleteRefreshTokenByIDCall wrap *gomock.Call
type MockUserRepositoryInterfaceDeleteRefreshTokenByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryInterfaceDeleteRefreshTokenByIDCall) Return(arg0 error) *MockUserRepositoryInterfaceDeleteRefreshTokenByIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryInterfaceDeleteRefreshTokenByIDCall) Do(f func(uint) error) *MockUserRepositoryInterfaceDeleteRefreshTokenByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryInterfaceDeleteRefreshTokenByIDCall) DoAndReturn(f func(uint) error) *MockUserRepositoryInterfaceDeleteRefreshTokenByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByEmail mocks base method.
func (m *MockUserRepositoryInterface) GetByEmail(email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetByEmail(email any) *MockUserRepositoryInterfaceGetByEmailCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetByEmail), email)
	return &MockUserRepositoryInterfaceGetByEmailCall{Call: call}
}

// MockUserRepositoryInterfaceGetByEmailCall wrap *gomock.Call
type MockUserRepositoryInterfaceGetByEmailCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryInterfaceGetByEmailCall) Return(arg0 *models.User, arg1 error) *MockUserRepositoryInterfaceGetByEmailCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryInterfaceGetByEmailCall) Do(f func(string) (*models.User, error)) *MockUserRepositoryInterfaceGetByEmailCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryInterfaceGetByEmailCall) DoAndReturn(f func(string) (*models.User, error)) *MockUserRepositoryInterfaceGetByEmailCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByEmailAndActive mocks base method.
func (m *MockUserRepositoryInterface) GetByEmailAndActive(email string, isActive bool) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmailAndActive", email, isActive)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmailAndActive indicates an expected call of GetByEmailAndActive.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetByEmailAndActive(email, isActive any) *MockUserRepositoryInterfaceGetByEmailAndActiveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmailAndActive", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetByEmailAndActive), email, isActive)
	return &MockUserRepositoryInterfaceGetByEmailAndActiveCall{Call: call}
}

// MockUserRepositoryInterfaceGetByEmailAndActiveCall wrap *gomock.Call
type MockUserRepositoryInterfaceGetByEmailAndActiveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryInterfaceGetByEmailAndActiveCall) Return(arg0 *models.User, arg1 error) *MockUserRepositoryInterfaceGetByEmailAndActiveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryInterfaceGetByEmailAndActiveCall) Do(f func(string, bool) (*models.User, error)) *MockUserRepositoryInterfaceGetByEmailAndActiveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryInterfaceGetByEmailAndActiveCall) DoAndReturn(f func(string, bool) (*models.User, error)) *MockUserRepositoryInterfaceGetByEmailAndActiveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockUserRepositoryInterface) GetByID(id uint) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetByID(id any) *MockUserRepositoryInterfaceGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetByID), id)
	return &MockUserRepositoryInterfaceGetByIDCall{Call: call}
}

// MockUserRepositoryInterfaceGetByIDCall wrap *gomock.Call
type MockUserRepositoryInterfaceGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryInterfaceGetByIDCall) Return(arg0 *models.User, arg1 error) *MockUserRepositoryInterfaceGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryInterfaceGetByIDCall) Do(f func(uint) (*models.User, error)) *MockUserRepositoryInterfaceGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryInterfaceGetByIDCall) DoAndReturn(f func(uint) (*models.User, error)) *MockUserRepositoryInterfaceGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetValidRefreshToken mocks base method.
func (m *MockUserRepositoryInterface) GetValidRefreshToken(token string) (*models.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidRefreshToken", token)
	ret0, _ := ret[0].(*models.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidRefreshToken indicates an expected call of GetValidRefreshToken.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetValidRefreshToken(token any) *MockUserRepositoryInterfaceGetValidRefreshTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidRefreshToken", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetValidRefreshToken), token)
	return &MockUserRepositoryInterfaceGetValidRefreshTokenCall{Call: call}
}

// MockUserRepositoryInterfaceGetValidRefreshTokenCall wrap *gomock.Call
type MockUserRepositoryInterfaceGetValidRefreshTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryInterfaceGetValidRefreshTokenCall) Return(arg0 *models.RefreshToken, arg1 error) *MockUserRepositoryInterfaceGetValidRefreshTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryInterfaceGetValidRefreshTokenCall) Do(f func(string) (*models.RefreshToken, error)) *MockUserRepositoryInterfaceGetValidRefreshTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryInterfaceGetValidRefreshTokenCall) DoAndReturn(f func(string) (*models.RefreshToken, error)) *MockUserRepositoryInterfaceGetValidRefreshTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockUserRepositoryInterface) Update(user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryInterfaceMockRecorder) Update(user any) *MockUserRepositoryInterfaceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepositoryInterface)(nil).Update), user)
	return &MockUserRepositoryInterfaceUpdateCall{Call: call}
}

// MockUserRepositoryInterfaceUpdateCall wrap *gomock.Call
type MockUserRepositoryInterfaceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryInterfaceUpdateCall) Return(arg0 error) *MockUserRepositoryInterfaceUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryInterfaceUpdateCall) Do(f func(*models.User) error) *MockUserRepositoryInterfaceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryInterfaceUpdateCall) DoAndReturn(f func(*models.User) error) *MockUserRepositoryInterfaceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockCartRepositoryInterface is a mock of CartRepositoryInterface interface.
type MockCartRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCartRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockCartRepositoryInterfaceMockRecorder is the mock recorder for MockCartRepositoryInterface.
type MockCartRepositoryInterfaceMockRecorder struct {
	mock *MockCartRepositoryInterface
}

// NewMockCartRepositoryInterface creates a new mock instance.
func NewMockCartRepositoryInterface(ctrl *gomock.Controller) *MockCartRepositoryInterface {
	mock := &MockCartRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockCartRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartRepositoryInterface) EXPECT() *MockCartRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCartRepositoryInterface) Create(cart *models.Cart) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", cart)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCartRepositoryInterfaceMockRecorder) Create(cart any) *MockCartRepositoryInterfaceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCartRepositoryInterface)(nil).Create), cart)
	return &MockCartRepositoryInterfaceCreateCall{Call: call}
}

// MockCartRepositoryInterfaceCreateCall wrap *gomock.Call
type MockCartRepositoryInterfaceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCartRepositoryInterfaceCreateCall) Return(arg0 error) *MockCartRepositoryInterfaceCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCartRepositoryInterfaceCreateCall) Do(f func(*models.Cart) error) *MockCartRepositoryInterfaceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCartRepositoryInterfaceCreateCall) DoAndReturn(f func(*models.Cart) error) *MockCartRepositoryInterfaceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockCartRepositoryInterface) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCartRepositoryInterfaceMockRecorder) Delete(id any) *MockCartRepositoryInterfaceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCartRepositoryInterface)(nil).Delete), id)
	return &MockCartRepositoryInterfaceDeleteCall{Call: call}
}

// MockCartRepositoryInterfaceDeleteCall wrap *gomock.Call
type MockCartRepositoryInterfaceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCartRepositoryInterfaceDeleteCall) Return(arg0 error) *MockCartRepositoryInterfaceDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCartRepositoryInterfaceDeleteCall) Do(f func(uint) error) *MockCartRepositoryInterfaceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCartRepositoryInterfaceDeleteCall) DoAndReturn(f func(uint) error) *MockCartRepositoryInterfaceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByUserID mocks base method.
func (m *MockCartRepositoryInterface) GetByUserID(userID uint) (*models.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", userID)
	ret0, _ := ret[0].(*models.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockCartRepositoryInterfaceMockRecorder) GetByUserID(userID any) *MockCartRepositoryInterfaceGetByUserIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockCartRepositoryInterface)(nil).GetByUserID), userID)
	return &MockCartRepositoryInterfaceGetByUserIDCall{Call: call}
}

// MockCartRepositoryInterfaceGetByUserIDCall wrap *gomock.Call
type MockCartRepositoryInterfaceGetByUserIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCartRepositoryInterfaceGetByUserIDCall) Return(arg0 *models.Cart, arg1 error) *MockCartRepositoryInterfaceGetByUserIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCartRepositoryInterfaceGetByUserIDCall) Do(f func(uint) (*models.Cart, error)) *MockCartRepositoryInterfaceGetByUserIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCartRepositoryInterfaceGetByUserIDCall) DoAndReturn(f func(uint) (*models.Cart, error)) *MockCartRepositoryInterfaceGetByUserIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockCartRepositoryInterface) Update(cart *models.Cart) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", cart)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCartRepositoryInterfaceMockRecorder) Update(cart any) *MockCartRepositoryInterfaceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCartRepositoryInterface)(nil).Update), cart)
	return &MockCartRepositoryInterfaceUpdateCall{Call: call}
}

// MockCartRepositoryInterfaceUpdateCall wrap *gomock.Call
type MockCartRepositoryInterfaceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCartRepositoryInterfaceUpdateCall) Return(arg0 error) *MockCartRepositoryInterfaceUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCartRepositoryInterfaceUpdateCall) Do(f func(*models.Cart) error) *MockCartRepositoryInterfaceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCartRepositoryInterfaceUpdateCall) DoAndReturn(f func(*models.Cart) error) *MockCartRepositoryInterfaceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockProductRepositoryInterface is a mock of ProductRepositoryInterface interface.
type MockProductRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockProductRepositoryInterfaceMockRecorder is the mock recorder for MockProductRepositoryInterface.
type MockProductRepositoryInterfaceMockRecorder struct {
	mock *MockProductRepositoryInterface
}

// NewMockProductRepositoryInterface creates a new mock instance.
func NewMockProductRepositoryInterface(ctrl *gomock.Controller) *MockProductRepositoryInterface {
	mock := &MockProductRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepositoryInterface) EXPECT() *MockProductRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProductRepositoryInterface) Create(product *models.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", product)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProductRepositoryInterfaceMockRecorder) Create(product any) *MockProductRepositoryInterfaceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProductRepositoryInterface)(nil).Create), product)
	return &MockProductRepositoryInterfaceCreateCall{Call: call}
}

// MockProductRepositoryInterfaceCreateCall wrap *gomock.Call
type MockProductRepositoryInterfaceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductRepositoryInterfaceCreateCall) Return(arg0 error) *MockProductRepositoryInterfaceCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductRepositoryInterfaceCreateCall) Do(f func(*models.Product) error) *MockProductRepositoryInterfaceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductRepositoryInterfaceCreateCall) DoAndReturn(f func(*models.Product) error) *MockProductRepositoryInterfaceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockProductRepositoryInterface) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProductRepositoryInterfaceMockRecorder) Delete(id any) *MockProductRepositoryInterfaceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProductRepositoryInterface)(nil).Delete), id)
	return &MockProductRepositoryInterfaceDeleteCall{Call: call}
}

// MockProductRepositoryInterfaceDeleteCall wrap *gomock.Call
type MockProductRepositoryInterfaceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductRepositoryInterfaceDeleteCall) Return(arg0 error) *MockProductRepositoryInterfaceDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductRepositoryInterfaceDeleteCall) Do(f func(uint) error) *MockProductRepositoryInterfaceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductRepositoryInterfaceDeleteCall) DoAndReturn(f func(uint) error) *MockProductRepositoryInterfaceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetAll mocks base method.
func (m *MockProductRepositoryInterface) GetAll(offset, limit int) ([]models.Product, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", offset, limit)
	ret0, _ := ret[0].([]models.Product)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockProductRepositoryInterfaceMockRecorder) GetAll(offset, limit any) *MockProductRepositoryInterfaceGetAllCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockProductRepositoryInterface)(nil).GetAll), offset, limit)
	return &MockProductRepositoryInterfaceGetAllCall{Call: call}
}

// MockProductRepositoryInterfaceGetAllCall wrap *gomock.Call
type MockProductRepositoryInterfaceGetAllCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductRepositoryInterfaceGetAllCall) Return(arg0 []models.Product, arg1 int64, arg2 error) *MockProductRepositoryInterfaceGetAllCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductRepositoryInterfaceGetAllCall) Do(f func(int, int) ([]models.Product, int64, error)) *MockProductRepositoryInterfaceGetAllCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductRepositoryInterfaceGetAllCall) DoAndReturn(f func(int, int) ([]models.Product, int64, error)) *MockProductRepositoryInterfaceGetAllCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockProductRepositoryInterface) GetByID(id uint) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockProductRepositoryInterfaceMockRecorder) GetByID(id any) *MockProductRepositoryInterfaceGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockProductRepositoryInterface)(nil).GetByID), id)
	return &MockProductRepositoryInterfaceGetByIDCall{Call: call}
}

// MockProductRepositoryInterfaceGetByIDCall wrap *gomock.Call
type MockProductRepositoryInterfaceGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductRepositoryInterfaceGetByIDCall) Return(arg0 *models.Product, arg1 error) *MockProductRepositoryInterfaceGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductRepositoryInterfaceGetByIDCall) Do(f func(uint) (*models.Product, error)) *MockProductRepositoryInterfaceGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductRepositoryInterfaceGetByIDCall) DoAndReturn(f func(uint) (*models.Product, error)) *MockProductRepositoryInterfaceGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Search mocks base method.
func (m *MockProductRepositoryInterface) Search(req *dto.SearchProductsRequest) ([]models.ProductsWithRank, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", req)
	ret0, _ := ret[0].([]models.ProductsWithRank)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Search indicates an expected call of Search.
func (mr *MockProductRepositoryInterfaceMockRecorder) Search(req any) *MockProductRepositoryInterfaceSearchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockProductRepositoryInterface)(nil).Search), req)
	return &MockProductRepositoryInterfaceSearchCall{Call: call}
}

// MockProductRepositoryInterfaceSearchCall wrap *gomock.Call
type MockProductRepositoryInterfaceSearchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductRepositoryInterfaceSearchCall) Return(arg0 []models.ProductsWithRank, arg1 int64, arg2 error) *MockProductRepositoryInterfaceSearchCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductRepositoryInterfaceSearchCall) Do(f func(*dto.SearchProductsRequest) ([]models.ProductsWithRank, int64, error)) *MockProductRepositoryInterfaceSearchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductRepositoryInterfaceSearchCall) DoAndReturn(f func(*dto.SearchProductsRequest) ([]models.ProductsWithRank, int64, error)) *MockProductRepositoryInterfaceSearchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockProductRepositoryInterface) Update(product *models.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", product)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProductRepositoryInterfaceMockRecorder) Update(product any) *MockProductRepositoryInterfaceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProductRepositoryInterface)(nil).Update), product)
	return &MockProductRepositoryInterfaceUpdateCall{Call: call}
}

// MockProductRepositoryInterfaceUpdateCall wrap *gomock.Call
type MockProductRepositoryInterfaceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductRepositoryInterfaceUpdateCall) Return(arg0 error) *MockProductRepositoryInterfaceUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductRepositoryInterfaceUpdateCall) Do(f func(*models.Product) error) *MockProductRepositoryInterfaceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductRepositoryInterfaceUpdateCall) DoAndReturn(f func(*models.Product) error) *MockProductRepositoryInterfaceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockCategoryRepositoryInterface is a mock of CategoryRepositoryInterface interface.
type MockCategoryRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockCategoryRepositoryInterfaceMockRecorder is the mock recorder for MockCategoryRepositoryInterface.
type MockCategoryRepositoryInterfaceMockRecorder struct {
	mock *MockCategoryRepositoryInterface
}

// NewMockCategoryRepositoryInterface creates a new mock instance.
func NewMockCategoryRepositoryInterface(ctrl *gomock.Controller) *MockCategoryRepositoryInterface {
	mock := &MockCategoryRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockCategoryRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoryRepositoryInterface) EXPECT() *MockCategoryRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCategoryRepositoryInterface) Create(category *models.Category) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", category)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCategoryRepositoryInterfaceMockRecorder) Create(category any) *MockCategoryRepositoryInterfaceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCategoryRepositoryInterface)(nil).Create), category)
	return &MockCategoryRepositoryInterfaceCreateCall{Call: call}
}

// MockCategoryRepositoryInterfaceCreateCall wrap *gomock.Call
type MockCategoryRepositoryInterfaceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCategoryRepositoryInterfaceCreateCall) Return(arg0 error) *MockCategoryRepositoryInterfaceCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCategoryRepositoryInterfaceCreateCall) Do(f func(*models.Category) error) *MockCategoryRepositoryInterfaceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCategoryRepositoryInterfaceCreateCall) DoAndReturn(f func(*models.Category) error) *MockCategoryRepositoryInterfaceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockCategoryRepositoryInterface) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCategoryRepositoryInterfaceMockRecorder) Delete(id any) *MockCategoryRepositoryInterfaceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCategoryRepositoryInterface)(nil).Delete), id)
	return &MockCategoryRepositoryInterfaceDeleteCall{Call: call}
}

// MockCategoryRepositoryInterfaceDeleteCall wrap *gomock.Call
type MockCategoryRepositoryInterfaceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCategoryRepositoryInterfaceDeleteCall) Return(arg0 error) *MockCategoryRepositoryInterfaceDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCategoryRepositoryInterfaceDeleteCall) Do(f func(uint) error) *MockCategoryRepositoryInterfaceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCategoryRepositoryInterfaceDeleteCall) DoAndReturn(f func(uint) error) *MockCategoryRepositoryInterfaceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetAll mocks base method.
func (m *MockCategoryRepositoryInterface) GetAll() ([]models.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]models.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockCategoryRepositoryInterfaceMockRecorder) GetAll() *MockCategoryRepositoryInterfaceGetAllCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockCategoryRepositoryInterface)(nil).GetAll))
	return &MockCategoryRepositoryInterfaceGetAllCall{Call: call}
}

// MockCategoryRepositoryInterfaceGetAllCall wrap *gomock.Call
type MockCategoryRepositoryInterfaceGetAllCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCategoryRepositoryInterfaceGetAllCall) Return(arg0 []models.Category, arg1 error) *MockCategoryRepositoryInterfaceGetAllCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCategoryRepositoryInterfaceGetAllCall) Do(f func() ([]models.Category, error)) *MockCategoryRepositoryInterfaceGetAllCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCategoryRepositoryInterfaceGetAllCall) DoAndReturn(f func() ([]models.Category, error)) *MockCategoryRepositoryInterfaceGetAllCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockCategoryRepositoryInterface) GetByID(id uint) (*models.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*models.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCategoryRepositoryInterfaceMockRecorder) GetByID(id any) *MockCategoryRepositoryInterfaceGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCategoryRepositoryInterface)(nil).GetByID), id)
	return &MockCategoryRepositoryInterfaceGetByIDCall{Call: call}
}

// MockCategoryRepositoryInterfaceGetByIDCall wrap *gomock.Call
type MockCategoryRepositoryInterfaceGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCategoryRepositoryInterfaceGetByIDCall) Return(arg0 *models.Category, arg1 error) *MockCategoryRepositoryInterfaceGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCategoryRepositoryInterfaceGetByIDCall) Do(f func(uint) (*models.Category, error)) *MockCategoryRepositoryInterfaceGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCategoryRepositoryInterfaceGetByIDCall) DoAndReturn(f func(uint) (*models.Category, error)) *MockCategoryRepositoryInterfaceGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockCategoryRepositoryInterface) Update(category *models.Category) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", category)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCategoryRepositoryInterfaceMockRecorder) Update(category any) *MockCategoryRepositoryInterfaceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCategoryRepositoryInterface)(nil).Update), category)
	return &MockCategoryRepositoryInterfaceUpdateCall{Call: call}
}

// MockCategoryRepositoryInterfaceUpdateCall wrap *gomock.Call
type MockCategoryRepositoryInterfaceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCategoryRepositoryInterfaceUpdateCall) Return(arg0 error) *MockCategoryRepositoryInterfaceUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCategoryRepositoryInterfaceUpdateCall) Do(f func(*models.Category) error) *MockCategoryRepositoryInterfaceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCategoryRepositoryInterfaceUpdateCall) DoAndReturn(f func(*models.Category) error) *MockCategoryRepositoryInterfaceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockProductImageRepositoryInterface is a mock of ProductImageRepositoryInterface interface.
type MockProductImageRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProductImageRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockProductImageRepositoryInterfaceMockRecorder is the mock recorder for MockProductImageRepositoryInterface.
type MockProductImageRepositoryInterfaceMockRecorder struct {
	mock *MockProductImageRepositoryInterface
}

// NewMockProductImageRepositoryInterface creates a new mock instance.
func NewMockProductImageRepositoryInterface(ctrl *gomock.Controller) *MockProductImageRepositoryInterface {
	mock := &MockProductImageRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockProductImageRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductImageRepositoryInterface) EXPECT() *MockProductImageRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProductImageRepositoryInterface) Create(image *models.ProductImage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", image)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProductImageRepositoryInterfaceMockRecorder) Create(image any) *MockProductImageRepositoryInterfaceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProductImageRepositoryInterface)(nil).Create), image)
	return &MockProductImageRepositoryInterfaceCreateCall{Call: call}
}

// MockProductImageRepositoryInterfaceCreateCall wrap *gomock.Call
type MockProductImageRepositoryInterfaceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductImageRepositoryInterfaceCreateCall) Return(arg0 error) *MockProductImageRepositoryInterfaceCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductImageRepositoryInterfaceCreateCall) Do(f func(*models.ProductImage) error) *MockProductImageRepositoryInterfaceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductImageRepositoryInterfaceCreateCall) DoAndReturn(f func(*models.ProductImage) error) *MockProductImageRepositoryInterfaceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetImagesCountByProductID mocks base method.
func (m *MockProductImageRepositoryInterface) GetImagesCountByProductID(productID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImagesCountByProductID", productID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImagesCountByProductID indicates an expected call of GetImagesCountByProductID.
func (mr *MockProductImageRepositoryInterfaceMockRecorder) GetImagesCountByProductID(productID any) *MockProductImageRepositoryInterfaceGetImagesCountByProductIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImagesCountByProductID", reflect.TypeOf((*MockProductImageRepositoryInterface)(nil).GetImagesCountByProductID), productID)
	return &MockProductImageRepositoryInterfaceGetImagesCountByProductIDCall{Call: call}
}

// MockProductImageRepositoryInterfaceGetImagesCountByProductIDCall wrap *gomock.Call
type MockProductImageRepositoryInterfaceGetImagesCountByProductIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProductImageRepositoryInterfaceGetImagesCountByProductIDCall) Return(arg0 int64, arg1 error) *MockProductImageRepositoryInterfaceGetImagesCountByProductIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProductImageRepositoryInterfaceGetImagesCountByProductIDCall) Do(f func(uint) (int64, error)) *MockProductImageRepositoryInterfaceGetImagesCountByProductIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProductImageRepositoryInterfaceGetImagesCountByProductIDCall) DoAndReturn(f func(uint) (int64, error)) *MockProductImageRepositoryInterfaceGetImagesCountByProductIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockCartItemRepositoryInterface is a mock of CartItemRepositoryInterface interface.
type MockCartItemRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCartItemRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockCartItemRepositoryInterfaceMockRecorder is the mock recorder for MockCartItemRepositoryInterface.
type MockCartItemRepositoryInterfaceMockRecorder struct {
	mock *MockCartItemRepositoryInterface
}

// NewMockCartItemRepositoryInterface creates a new mock instance.
func NewMockCartItemRepositoryInterface(ctrl *gomock.Controller) *MockCartItemRepositoryInterface {
	mock := &MockCartItemRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockCartItemRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartItemRepositoryInterface) EXPECT() *MockCartItemRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCartItemRepositoryInterface) Create(cartItem *models.CartItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", cartItem)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCartItemRepositoryInterfaceMockRecorder) Create(cartItem any) *MockCartItemRepositoryInterfaceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCartItemRepositoryInterface)(nil).Create), cartItem)
	return &MockCartItemRepositoryInterfaceCreateCall{Call: call}
}

// MockCartItemRepositoryInterfaceCreateCall wrap *gomock.Call
type MockCartItemRepositoryInterfaceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCartItemRepositoryInterfaceCreateCall) Return(arg0 error) *MockCartItemRepositoryInterfaceCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCartItemRepositoryInterfaceCreateCall) Do(f func(*models.CartItem) error) *MockCartItemRepositoryInterfaceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCartItemRepositoryInterfaceCreateCall) DoAndReturn(f func(*models.CartItem) error) *MockCartItemRepositoryInterfaceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockCartItemRepositoryInterface) Delete(userID, itemID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", userID, itemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCartItemRepositoryInterfaceMockRecorder) Delete(userID, itemID any) *MockCartItemRepositoryInterfaceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCartItemRepositoryInterface)(nil).Delete), userID, itemID)
	return &MockCartItemRepositoryInterfaceDeleteCall{Call: call}
}

// MockCartItemRepositoryInterfaceDeleteCall wrap *gomock.Call
type MockCartItemRepositoryInterfaceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCartItemRepositoryInterfaceDeleteCall) Return(arg0 error) *MockCartItemRepositoryInterfaceDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCartItemRepositoryInterfaceDeleteCall) Do(f func(uint, uint) error) *MockCartItemRepositoryInterfaceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCartItemRepositoryInterfaceDeleteCall) DoAndReturn(f func(uint, uint) error) *MockCartItemRepositoryInterfaceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByCartAndProduct mocks base method.
func (m *MockCartItemRepositoryInterface) GetByCartAndProduct(cartID, productID uint) (*models.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCartAndProduct", cartID, productID)
	ret0, _ := ret[0].(*models.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCartAndProduct indicates an expected call of GetByCartAndProduct.
func (mr *MockCartItemRepositoryInterfaceMockRecorder) GetByCartAndProduct(cartID, productID any) *MockCartItemRepositoryInterfaceGetByCartAndProductCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCartAndProduct", reflect.TypeOf((*MockCartItemRepositoryInterface)(nil).GetByCartAndProduct), cartID, productID)
	return &MockCartItemRepositoryInterfaceGetByCartAndProductCall{Call: call}
}

// MockCartItemRepositoryInterfaceGetByCartAndProductCall wrap *gomock.Call
type MockCartItemRepositoryInterfaceGetByCartAndProductCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCartItemRepositoryInterfaceGetByCartAndProductCall) Return(arg0 *models.CartItem, arg1 error) *MockCartItemRepositoryInterfaceGetByCartAndProductCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCartItemRepositoryInterfaceGetByCartAndProductCall) Do(f func(uint, uint) (*models.CartItem, error)) *MockCartItemRepositoryInterfaceGetByCartAndProductCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCartItemRepositoryInterfaceGetByCartAndProductCall) DoAndReturn(f func(uint, uint) (*models.CartItem, error)) *MockCartItemRepositoryInterfaceGetByCartAndProductCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByCartIDAndProductID mocks base method.
func (m *MockCartItemRepositoryInterface) GetByCartIDAndProductID(cartID, productID uint) ([]models.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCartIDAndProductID", cartID, productID)
	ret0, _ := ret[0].([]models.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCartIDAndProductID indicates an expected call of GetByCartIDAndProductID.
func (mr *MockCartItemRepositoryInterfaceMockRecorder) GetByCartIDAndProductID(cartID, productID any) *MockCartItemRepositoryInterfaceGetByCartIDAndProductIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCartIDAndProductID", reflect.TypeOf((*MockCartItemRepositoryInterface)(nil).GetByCartIDAndProductID), cartID, productID)
	return &MockCartItemRepositoryInterfaceGetByCartIDAndProductIDCall{Call: call}
}

// MockCartItemRepositoryInterfaceGetByCartIDAndProductIDCall wrap *gomock.Call
type MockCartItemRepositoryInterfaceGetByCartIDAndProductIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCartItemRepositoryInterfaceGetByCartIDAndProductIDCall) Return(arg0 []models.CartItem, arg1 error) *MockCartItemRepositoryInterfaceGetByCartIDAndProductIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCartItemRepositoryInterfaceGetByCartIDAndProductIDCall) Do(f func(uint, uint) ([]models.CartItem, error)) *MockCartItemRepositoryInterfaceGetByCartIDAndProductIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCartItemRepositoryInterfaceGetByCartIDAndProductIDCall) DoAndReturn(f func(uint, uint) ([]models.CartItem, error)) *MockCartItemRepositoryInterfaceGetByCartIDAndProductIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByUserIDAndItemID mocks base method.
func (m *MockCartItemRepositoryInterface) GetByUserIDAndItemID(userID, itemID uint) (*models.CartItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserIDAndItemID", userID, itemID)
	ret0, _ := ret[0].(*models.CartItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserIDAndItemID indicates an expected call of GetByUserIDAndItemID.
func (mr *MockCartItemRepositoryInterfaceMockRecorder) GetByUserIDAndItemID(userID, itemID any) *MockCartItemRepositoryInterfaceGetByUserIDAndItemIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserIDAndItemID", reflect.TypeOf((*MockCartItemRepositoryInterface)(nil).GetByUserIDAndItemID), userID, itemID)
	return &MockCartItemRepositoryInterfaceGetByUserIDAndItemIDCall{Call: call}
}

// MockCartItemRepositoryInterfaceGetByUserIDAndItemIDCall wrap *gomock.Call
type MockCartItemRepositoryInterfaceGetByUserIDAndItemIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCartItemRepositoryInterfaceGetByUserIDAndItemIDCall) Return(arg0 *models.CartItem, arg1 error) *MockCartItemRepositoryInterfaceGetByUserIDAndItemIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCartItemRepositoryInterfaceGetByUserIDAndItemIDCall) Do(f func(uint, uint) (*models.CartItem, error)) *MockCartItemRepositoryInterfaceGetByUserIDAndItemIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCartItemRepositoryInterfaceGetByUserIDAndItemIDCall) DoAndReturn(f func(uint, uint) (*models.CartItem, error)) *MockCartItemRepositoryInterfaceGetByUserIDAndItemIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockCartItemRepositoryInterface) Update(cartItem *models.CartItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", cartItem)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCartItemRepositoryInterfaceMockRecorder) Update(cartItem any) *MockCartItemRepositoryInterfaceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCartItemRepositoryInterface)(nil).Update), cartItem)
	return &MockCartItemRepositoryInterfaceUpdateCall{Call: call}
}

// MockCartItemRepositoryInterfaceUpdateCall wrap *gomock.Call
type MockCartItemRepositoryInterfaceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCartItemRepositoryInterfaceUpdateCall) Return(arg0 error) *MockCartItemRepositoryInterfaceUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCartItemRepositoryInterfaceUpdateCall) Do(f func(*models.CartItem) error) *MockCartItemRepositoryInterfaceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCartItemRepositoryInterfaceUpdateCall) DoAndReturn(f func(*models.CartItem) error) *MockCartItemRepositoryInterfaceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
